[LegalNotice]
Accepted=true

[Preferences]
WebUI\Port=8080
WebUI\Username=admin
WebUI\Password_PBKDF2="@ByteArray(ARQ77eY1NUZaQsuDHbIMCA==:0WMRkYTUWVT9wVvdDtHAjU9b3b7uB8NR1Gur2hmQCvCDpm39Q+PsJRJPaCU51dEiz+dTzh8qbPsL8WkFljQYFQ==)"
WebUI\LocalHostAuth=false
WebUI\HostHeaderValidation=false
WebUI\CSRFProtection=false
Downloads\SavePath=/downloads
Downloads\TempPath=/downloads/temp
Connection\PortRangeMin=6881
Connection\UPnP=false
Bittorrent\MaxRatio=0
Bittorrent\MaxRatioAction=1
Bittorrent\MaxSeedingMinutes=0
